/**
 * Drawing Script Types
 * Types for the "边画边讲" (Draw and Explain) feature
 */

import { DrawingShape } from "@/components/drawing-canvas";

// Drawing script generated by Claude
export interface DrawingScript {
  title: string;           // Topic/theme of the drawing
  opening: string;         // Opening narration
  steps: DrawingScriptStep[];  // Step-by-step instructions
  closing: string;         // Closing/summary narration
}

// A single step in the drawing script
export interface DrawingScriptStep {
  id: string;              // Unique step identifier
  narration: string;       // Text to be spoken via TTS
  shapes?: DrawingShape[]; // Shapes to draw during this step
  delayBefore?: number;    // Delay in ms before starting this step
  clearBefore?: boolean;   // Whether to clear canvas before drawing
}

// Execution state for the draw-explain feature
export type DrawExplainState =
  | "idle"           // Not started
  | "generating"     // Generating script from Claude
  | "executing"      // Executing script (TTS + drawing)
  | "paused"         // Execution paused
  | "completed"      // Script execution completed
  | "error";         // Error occurred

// Progress information during execution
export interface DrawExplainProgress {
  currentStepIndex: number;
  totalSteps: number;
  currentPhase: "opening" | "step" | "closing";
  isPlaying: boolean;
}

// Request to generate a drawing script
export interface DrawExplainGenerateRequest {
  userQuery: string;       // User's question/request
  videoContext?: string;   // Current video context
  videoId?: string;        // Video ID for RAG
  currentTime?: number;    // Current playback time
}

// Response from the generate API
export interface DrawExplainGenerateResponse {
  script: DrawingScript;
  error?: string;
}

// Voice mode types
export type VoiceMode = "realtime" | "draw_explain" | "volcengine_rtc";

// Voice backend types
export type VoiceBackend = "doubao_realtime" | "doubao" | "volcengine_rtc";
